openapi: 3.0.0
info:
  title: Аренда ресурсов облачного сервиса
  version: 0.0.1
servers:
  - url: http://localhost:8080/api/v1/
    description: Dev servers
paths:
  /clouds:
    get:
      summary: Метод получения списка ресурсов на облако
      tags:
        - Clouds
      operationId: getAllClouds
      responses: 
        "200":
          description: Успешный ответ на запрос
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Clouds"
        "default":
          description: Всё остальное
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    post:
      summary: Создание заказа на облако
      tags:
        - Clouds
      operationId: createCloud
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Clouds"
      responses:
        "200":
          description: Успешный ответ на запрос
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Clouds"
        "default":
          description: Всё остальное
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /cloud/{cloudID}:
    delete:
      summary: Отмена заказа по ID
      tags:
        - Clouds
      operationId: cancelCloudByID
      parameters:
        - name: cloudID
          in: path
          required: true
          description: ID заказа на облако
          schema:
            type: string
          example: f1234j5678
      responses:
        "200":
          description: Отмена прошла успешно
          content:
            application/json: {}
        "404":
          description: Заказ не найден
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "default":
          description: Всё остальное
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /cloud/{clientID}/{RAM}:
    put:
      summary: Изменение арендуемого объёма памяти
      tags:
        - Clouds
      parameters:
        - name: clientID
          in: path
          required: true
          description: ID клиента
          schema:
            type: string
          example: f1234j5678
        - name: RAM
          in: path
          required: true
          description: Изменение объёма памяти
          schema:
            type: integer
          example: 516
      operationId: changeCloud
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Clouds"
      responses:
        "200":
          description: Успешное изменение объёма памяти
          content:
            application/json: {}
        "404":
          description: ClientID не найден
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "default":
          description: Все остальные ответы
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Cloud:
      type: object
      required:
        - id_client
        - OS
        - RAM
        - CPU
        - SSD
      properties:
        cloudID:
          type: string
          example: f1234j5678
        clientID:
          type: string
          example: f1234j5678
        OS:
          type: string
          enum:
            - Linux
            - Windows
        RAM:
          type: integer
          example: 256
        CPU:
          type: string
          example: 4
        SSD:
          type: string
          example: 1024
    Clouds:
      type: array
      items:
        $ref: "#/components/schemas/Cloud"
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
        message:
          type: string
